services:
  postgres:
    image: postgres:16
    container_name: geodouro-postgres
    environment:
      POSTGRES_DB: geodouro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - geodouro_postgres_data:/var/lib/postgresql/data

volumes:
  geodouro_postgres_data:
